### ISSUE TITLE
Post Deliverable Checklist: January 30th

### ISSUE THREAD

**Issue by jenniferyaya** [jenniferyaya/simple-chat-app#8]
@ericadamski 
@xuke918 
@anthonyaubrey 

Ke
# Progress
- [x] Paper Wireframes
- [x] Member list
# Issues
Completed the created issue about wireframe for different screens for Member List.
# Positive
- I did research when I sketch the paper wireframe for member list. I feel it is very useful and it helps me to know more about chat app's member list.
- I feel using project and issues at github for milestone are very useful. It allows me to tracking the progress very easily.
# Improvement
- When I drawing member list sketches for different screens, I feel confused because the member list for small, medium, large screens all looks similar. 
# Feedback
- Is there anything special I need to pay attention to during design the member list? Or what does success look at paper wireframe stage of the process?

Anthony
- [x] Created login page wireframe
- [x] Created issue for paper wireframe (login screen)

-I felt good about the amount of work I was tasked with completing. 
-I found working through the project section to be a positive experience. 
-I found dividing up the wire frames amongst the group created a less cohesive overall theme.

### **Jennifer**
- [x] Paper wireframes for main chat page completed
- [x] Notification: joined/left

**Positive:**
- The challenge of designing something we haven't done
- Time allotted gave me the space do research

**Hurdles:**
-  Scary diving it since I felt unsure of what a chat app look like since I don't use them
- Procrastinating with the allotted time (double-edge sword)

**Feedback @ericadamski **
Is the direction of our idea meeting up with your expectations?

**Comment by ericadamski** [comment]
I will talk about my expectations a little in class, but in general I don't have any. I am Excited to see you all take a different path with the project :)
